<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>ValkeyDotNet.Tests</AssemblyName>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="NSubstitute" />
        <PackageReference Include="NSubstitute.Analyzers.CSharp" PrivateAssets="all" />
    </ItemGroup>
</Project>
